### ISSUE TITLE
Be careful! image-rs is so slow

### ISSUE THREAD

**Issue by DCjanus** [nicolashahn/diffimg-rs#4]
I've seen [this post](https://www.nicolas-hahn.com/python/go/rust/programming/2019/07/01/program-in-python-go-rust/) and found this repo.

I noticed that you are using image-rs in this repo, and I got to say, image-rs is very slow, see [this issue](https://github.com/image-rs/image-png/issues/61) and [this line](https://github.com/image-rs/image-png/blob/104b08036bf926d10fa96cec40b3134d337cccbf/src/decoder/mod.rs#L414-L415).

In my test case, sometimes it's even slower than the Go standard library.(too many memory alloc).

If you want to improve this crate, it might be a good idea to find another image crate.

But I am not concerned about the image processing, so I don't know if there is such a crate in Rust.

**Comment by Shnatsel** [comment]
`image` has improved considerably since. The issue you've linked is now fixed, and PNG decoding in particular should now competitive with pure libpng, starting with `png` crate version 0.16.5. In my tests decoding a PNG and writing it out in uncompressed form via image-rs is 10x faster than imagemagick.

JPEG decoding could still be improved though: https://github.com/image-rs/jpeg-decoder/issues/155

**Comment by DCjanus** [comment]
Good News!
